export const START_FETCHING_PRODUCT = 'features/Product/START_FETCHING_PRODUCT'
export const ERROR_FETCHING_PRODUCT = 'features/Product/ERROR_FETCHING_PRODUCT'
export const SUCCESS_FETCHING_PRODUCT =
  'features/Product/SUCCESS_FETCHING_PRODUCT'
export const START_FETCHING_SINGLE = 'features/Product/START_FETCHING_SINGLE'
export const SET_KEYWORD = 'features/Product/SET_KEYWORD'
export const SET_LIMIT = 'features/Product/SET_LIMIT'
export const SET_PAGE = 'features/Product/SET_PAGE'
export const NEXT_PAGE = 'features/Product/NEXT_PAGE'
export const PREV_PAGE = 'features/Product/PREV_PAGE'
export const SUCCESS_EDIT = 'features/Product/SUCCESS_EDIT'
export const SET_CATEGORY = 'features/Product/SET_CATEGORY'
export const FETCHING_ASC = 'features/Product/FETCHING_ASC'
export const FETCHING_DESC = 'features/Product/FETCHING_DESC'
export const FETCHING_TIMENEWS = 'features/Product/FETCHING_TIMENEWS'
export const SET_DATASEMI_CART = 'features/Product/SET_DATASEMI_CART'
