// export const ADD_ITEM = 'features/Cart/ADD_ITEM'
// export const REMOVE_ITEM = 'features/Cart/REMOVE_ITEM'
// export const CLEAR_ITEMS = 'features/Cart/CLEAR_ITEMS'
// export const SET_ITEMS = 'features/Cart/SET_ITEMS'
// export const FETCHING_DATA_CART = 'features/Cart/FETCHING_DATA_CART'
export const SUCCESS_FETCHING_CART = 'features/Cart/SUCCESS_FETCHING_CART'

export const ADD_ITEM = 'features/Cart/ADD_ITEM'
export const REMOVE_ITEM = 'features/Cart/REMOVE_ITEM'
export const CLEAR_ITEMS = 'features/Cart/CLEAR_ITEMS'
export const SET_ITEMS = 'features/Cart/SET_ITEMS'
export const DELELTE_VARIANT_OPTION = 'features/Cart/DELELTE_VARIANT_OPTION'
